## commentSubject 评论板块
@moduleUrl = /comment

### 获取评论板块列表
GET {{ baseUrl }}{{ moduleUrl }}/getComment
Content-Type: application/json
Authorization: Bearer {{ token }}

###新增评论接口
POST {{ baseUrl }}{{ moduleUrl }}/createComment
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "comtSubjectId":"",
    "commentId":5,
    "text":"666",
    "userId":""
}

###删除评论接口
POST {{ baseUrl }}{{ moduleUrl }}/deleteComment
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "comtSubjectId":"",
    "commentId":2
}

###恢复评论接口
POST {{ baseUrl }}{{ moduleUrl }}/recoverComment
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "comtSubjectId":"",
    "commentId":2
}

###获赞接口
PUT {{ baseUrl }}{{ moduleUrl }}/thumbsUp
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "commentId":2,
    "comtSubjectId":"",
    "userId":""
}
###取消点赞接口
PUT {{ baseUrl }}{{ moduleUrl }}/cancelThumbsUp
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "userId":"",
    "commentId":2,
    "comtSubjectId":""
    
}
###查询历史评论接口
GET {{ baseUrl }}{{ moduleUrl }}/getHistoryComment
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "userId":""
}
###查询点赞评论接口
GET {{ baseUrl }}{{ moduleUrl }}/getLoveComment
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "userId":""
}