## commentSubject 评论体板块
@moduleUrl = /commentSubject

### 获取评论体板块列表
GET {{ baseUrl }}{{ moduleUrl }}/getAllCommentSubject
Content-Type: application/json
Authorization: Bearer {{ token }}

###创建评论体接口
POST {{ baseUrl }}{{ moduleUrl }}/createCommentSubject
Content-Type: application/json

{
    "cbImg":"",
    "cbText":"牛逼",
    "cbTitle":"陈广文",
    "userId":"0190d0a9-721c-7664-a444-e4e10ec3d54c"
}
###修改评论体接口
PUT {{ baseUrl }}{{ moduleUrl }}/modifyCommentSubject
Content-Type: application/json

{
    "comtSubjectId":"",
    "userId":"",
    "cbImg":"",
    "cbText":"",
    "cbTitle":""
    
}

###删除评论体接口
POST {{ baseUrl }}{{ moduleUrl }}/deleteCommentSubject
Content-Type: application/json

{
    "comtSubjectId":"0190e366-04fa-7ef5-a0f8-bbd67ec1e3fa"
}
###恢复评论体接口
POST {{ baseUrl }}{{ moduleUrl }}/recoverCommentSubject
Content-Type: application/json

{
    "comtSubjectId":"0190e366-04fa-7ef5-a0f8-bbd67ec1e3fa"
}
###用户个人获取收藏评论体信息
GET {{ baseUrl }}{{ moduleUrl }}/getCollectCommentSubject
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "userId":"0190c9e4-684a-7070-a326-d0b5c07d65b0"
}
###用户收藏评论体接口
PUT {{ baseUrl }}{{ moduleUrl }}/collectCommentSubject
Content-Type: application/json
Authorization: Bearer {{ token }}

{ 
    "userId":"0190c9e4-684a-7070-a326-d0b5c07d65b0",
    "comtSubjectId":"01910e1a-0c8b-7225-b6af-1fe6f08032d6"
}
###用户取消收藏评论体接口
PUT {{ baseUrl }}{{ moduleUrl }}/cancelCollectCommentSubject
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "comtSubjectId":"0190e366-04fa-7ef5-a0f8-bbd67ec1e3fa",
    "userId":"0190c9e4-684a-7070-a326-d0b5c07d65b0"
}