# home 首页模块
@moduleUrl = /home

### 获取评论信息
GET {{ baseUrl }}{{ moduleUrl }}/commentInfo
Content-Type: application/json
Authorization: Bearer {{ token }}

### 获取评论对象信息
GET {{ baseUrl }}{{ moduleUrl }}/commentSubjectInfo
Content-Type: application/json
Authorization: Bearer {{ token }}
